#!/usr/bin/env bash

read -r -p "Are you sure you want to proceed? (y/n): " choice
case "$choice" in
  [Yy])
    echo "Proceeding..."
    ;;
  [Nn])
    echo "Cancelled."
    exit 1
    ;;
  *)
    echo "Invalid choice. Please enter 'y' or 'n'."
    exit 1
    ;;
esac

current_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

cd "$current_script_dir" || exit

terraform destroy --auto-approve && terraform apply --auto-approve
