@startuml use case
left to right direction
actor User

rectangle "Social Media" {
    User -- (Sign Up)
    User -- (Sign In)
    User -- (View Profile)
    User -- (Create Post)
    User -- (Search)
    User -- (View Notifications)
    User -- (Follow User)
    User -- (Unfollow User)
    (View Profile) ..> (Update Profile) : <<include>>
    (Create Post) ..> (View Post) : <<extends>>
    (View Post) ..> (Edit Post) : <<include>>
    (View Post) ..> (Delete Post) : <<include>>
    (View Post) ..> (Comment on Post) : <<include>>
    (Comment on Post) ..> (Edit Comment) : <<include>>
    (Comment on Post) ..> (Delete Comment) : <<include>>
    (View Post) ..> (React to Post) : <<include>>
    (React to Post) ..> (Remove Reaction) : <<include>>
    (View Post) ..> (Send Message) : <<include>>
    (Send Message) ..> (View Messages) : <<include>>
    (View Messages) ..> (Edit Message) : <<include>>
    (View Messages) ..> (Delete Message) : <<include>>
    (View Notifications) ..> (Delete Notification) : <<include>>
}
@enduml